apiVersion: apps/v1
kind: Deployment
metadata:
  name: bpdmswinningtransaction
spec:
  replicas: 1  
  selector:
    matchLabels:
      app: bpdmswinningtransaction
  template:
    metadata:
      labels:
        app: bpdmswinningtransaction
    spec:
      containers:
        - name: bpdmswinningtransaction
          image: cstaruatregistry.azurecr.io/bpdmswinningtransaction
          ports:
            - containerPort: 8080
          envFrom:
            - secretRef:
                name: postgres-credentials
            - secretRef:
                name: bpdmswinningtransaction
            - configMapRef:
                name: eventhub-logging
            - configMapRef:
                name: eventhub-common
            - configMapRef:
                name: bpdmswinningtransaction
            - configMapRef:
                name: jvm                
      hostAliases:
        - hostnames:
            - bpd-event-uat.servicebus.windows.net
          ip: 10.70.67.5
