apiVersion: apps/v1
kind: Deployment
metadata:
  name: bpdmswinningtransaction
spec:
  replicas: 1  
  selector:
    matchLabels:
      app: bpdmswinningtransaction
  template:
    metadata:
      labels:
        app: bpdmswinningtransaction
    spec:
      containers:
        - name: bpdmswinningtransaction
          image: cstarprodregistry.azurecr.io/bpdmswinningtransaction
          ports:
            - containerPort: 8080
          envFrom:
            - secretRef:
                name: postgres-credentials
            - configMapRef:
                name: eventhub-logging
            - configMapRef:
                name: bpdmswinningtransaction
            - configMapRef:
                name: jvm                
      hostAliases:
        - hostnames:
            - u87cstarprod.servicebus.windows.net
          ip: 10.70.132.4
