apiVersion: apps/v1
kind: Deployment
metadata:
  name: bpdmswinningtransaction
spec:
  replicas: 1
  selector:
    matchLabels:
      app: bpdmswinningtransaction
  template:
    metadata:
      labels:
        app: bpdmswinningtransaction
    spec:
      containers:
        - name: bpdmswinningtransaction
          image: cstardacr.azurecr.io/bpdmswinningtransaction
          ports:
            - containerPort: 8080
          envFrom:
            - secretRef:
                name: postgres-credentials
            - secretRef:
                name: bpdmswinningtransaction
            - configMapRef:
                name: eventhub-logging
            - configMapRef:
                name: eventhub-common
            - configMapRef:
                name: bpdmswinningtransaction
            - configMapRef:
                name: jvm
          livenessProbe:
            httpGet:
              path: /actuator/health
              port: 8080
              scheme: HTTP
            timeoutSeconds: 5
            periodSeconds: 10
            successThreshold: 1
            failureThreshold: 5
          readinessProbe:
            httpGet:
              path: /actuator/health
              port: 8080
              scheme: HTTP
            timeoutSeconds: 5
            periodSeconds: 10
            successThreshold: 1
            failureThreshold: 3
          startupProbe:
            httpGet:
              path: /actuator/health
              port: 8080
              scheme: HTTP
            initialDelaySeconds: 20
            timeoutSeconds: 5
            periodSeconds: 10
            successThreshold: 1
            failureThreshold: 30
          imagePullPolicy: Always

